// 01 Even Fibonacci Numbers
// attempt02.js
// File to be added to https://github.com/JamieBort/LearningDirectory/tree/master/JavaScript/CodingChallenges/ProjectEuler/EvenFibonacciNumbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// summation = (argument1, argument2) => argument1 + argument2; // keep this one
summation = (argument1, argument2) => {
	// delete this one
	sum = argument1 + argument2;
	console.log('argument2 + argument1: ', argument2, '+', argument1, '=', sum);
	return sum;
};

integer1 = 1;
integer2 = 2;
integer3 = 2;

function generation() {
	total = 0;
	// limit = 22;
	limit = 4000000;
	console.log('the two terms are less than:', limit);
	while (integer1 < limit) {
		console.log('integer1: ', integer1);
		console.log('integer3: ', integer3);
		integer1 = summation(integer1, integer3);
		integer3 = integer2;
		integer2 = integer1;
		console.log('integer1: ', integer1);
		console.log('integer3: ', integer3);
		console.log('--------');
		// t++;

		// summing the even values
		if (integer1 % 2 === 0) {
			console.log('---------------------------------------');
			console.log('calculating the sum of the even numbers');
			console.log('this term is even:', integer1);
			console.log('integer1: ', integer1);
			console.log('total: ', total);
			total += integer1;
			// console.log('sum of evens: ', total, '+', integer1, '=', total);
			console.log('---------------------------------------');
		}
	}
	console.log('sum of the even numbers: ', total);
}
generation();
