// 01 Even Fibonacci Numbers
// File to be added to https://github.com/JamieBort/LearningDirectory/tree/master/JavaScript/CodingChallenges/ProjectEuler/EvenFibonacciNumbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

summation = (num1, num2) => num1 + num2;
num3 = 1;
num4 = 2;
num5 = 2;

function generation(j) {
	t = 0;
	total = 0;
	while (t < j) {
		num3 = summation(num3, num5);
		num5 = num4;
		num4 = num3;
		console.log('num3', num3);
		t++;
		if (num3 % 2 === 0) {
			console.log('even', num3);
			total += num3;
		}
	}
}
generation(12);
console.log('total', total);
