// from: https://projecteuler.net/problem=2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// var a = 1;
// var b = 2;
// var array = [1,2];
// array.push(a);
// array.push(b);
// array.push(a + b);
function FibonacciSequence(n) {
    var array = [1, 2];

    // console.log(array);
    for (i = 0; i < (n); i++) {

        // if (array.length > 4) {
        //     array.pop();
        // }

        if ((i > 6) && (i < n - 7)) {
            array.splice(0, 1);
            if (array.length > 10) {
            array.pop();
        }
        }

        array.push(array[i] + array[i + 1]);
        console.log(array);
        
        // for (J = 0; J < (n); J++) {
        // if (i>(n-4)){
        // array.pop();
        // console.log(array);
        // array.splice(0, 1);
        // array.shift();
        // console.log(array);
        console.log(array.length);
    }
    // // console.log(array);
    // array.splice(0, 1);
    // console.log(array);
    // array.splice(0, 1);
    // console.log(array);
    // array.splice(0, 1);
    // console.log(array);
    // array.splice(0, 1);
    // console.log(array);
    // array.splice(0, 1);
    // console.log(array);

}
FibonacciSequence(20);

// var array2 = [0, 1, 2, 3, 4, 5, 6];
// console.log(array2.length);
// for (i = 0; i <array2.length; i++) {
    // array2.splice(0, 1);
    // array2.shift();
    // console.log(array2);
// }