print("This program calculates the average of two numbers.")
number1 = float(input("Please enter the first number: "))
print("You entered: ", number1)
number2 = float(input("Please enter the second number: "))
print("You entered: ", number2)
print("The average of ", number1, " and ", number2, " is: " , (number1+number2)/2)